### ISSUE TITLE
Unable to convert raw data.

### ISSUE THREAD

**Issue by BioinformaticEmilio** [chasemc/IDBac_App#11]
Hi,

I have no trouble viewing the translated example data set, but I can't manage to convert my raw data. I get the following message '' [number] files turned into 0 open data format files''. Could you help?

**Comment by chasemc** [comment]
I'd be glad to help.  

1.  Were you able to convert the raw data in the example dataset?
2.  If so, check if there any spaces or special characters in the file-names 
     and the names of the folders the data is in.
         -  Currently we are unable to process files when there is a space in the file path.  This will be fixed in 
             later versions.

Please let me know if this helps.

**Comment by BioinformaticEmilio** [comment]
Thanks!

1. Unfortunately not... same message.
2. No special characters. Folders are named [0_A1,0_A2,...,0_P16], files are in similar format [A1pA-A1] .

If it helps... I first installed IDBac, then realised I needed mzr and ggrepell. Uninstalled IDBac, installed both packages, then IDBac again.
--

**Comment by chasemc** [comment]
Woops! MSConvert.exe has to be added manually into the compiling script and it looks like somebody (me) missed it this last time. 

**Manual fix:**
Download msconvert.exe from the link below and then on your computer navigate to where you installed IDBac (defaults to "Documents" folder)  and paste the downloaded msconvert.exe into the folder named "pwiz".
[https://drive.google.com/open?id=1jbzRmng4zzf7Dzlq44GFU8YRkpLFJSk6
](https://drive.google.com/open?id=1jbzRmng4zzf7Dzlq44GFU8YRkpLFJSk6
)


**Updated Executable**
I will re-compile IDBac tonight with the latest updates as well, and make sure msconvert is present. I will update this post when I do.

Sorry for the inconvenience. 
-Chase

**Comment by chasemc** [comment]
This should be fixed in the new version of IDBac.

It may be downloaded here:
[ https://drive.google.com/open?id=0B0n1AhTXfxHqSmJFSHEyWjdaNmM]( https://drive.google.com/open?id=0B0n1AhTXfxHqSmJFSHEyWjdaNmM)

**Comment by BioinformaticEmilio** [comment]
Thanks for the quick reply!

Tried first the manual fix= same issue.
Installed new compilation= same issue... Both my data and the example files.

Am I missing something???

**Comment by chasemc** [comment]
Thanks for your patience working through this!

Last night I installed and successfully ran IDBac on a clean-install of windows, so I think something funky is going on.  

Things to consider, from Easy to Hard:
1.  I know I already suggested this, but check again the entire file-path of your raw data and where you select the IDBac working directory. If there is a space anywhere, msconvert will get mad.
     - eg " file path -> C:\Users\chase\Documents\New Folder\Data" will fail because of the space "New folder"

2.  Are you running 64bit or 32bit Windows?
If you're unsure, you can check here:
https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq
      - If you are running 32bit, please stop here and respond.  I overlooked the necessity of this before, but we may need 32 & 64 bit versions of IDBac.

3. Proteowizard can be finicky, so that would be the next check. You can use a tool Ming and I wrote for GNPS.
- The download and instructions can be found under "Data Conversion-Easy". 
https://bix-lab.ucsd.edu/display/Public/Data+Conversion+to+GNPS+Compatible+Formats+-+.mzXML+and+.mzML

   - After downloading, unzip the folder and Double-click the "Double-Click_To-Convert" file.  A command window should appear, once it disappears there should be a "thermo_file.mzXML" file in "Output_Folder".

- If this doesn't work it means your computer is missing some service packs Proteowizard requires to function. They can be installed using that same GNPS tool:

> Install windows libraries in "pwizLibraries-and-Installation" - Run appropriate program for 32-bit (32-Bit_Double-Click_To_Install.bat) or 64-bit system (64-Bit_Double-Click_To_Install.bat). To find out which type of OS you have please check here . 



4. Upload your data folder to:
https://drive.google.com/drive/folders/1C1FEw5xCXjnT0unSUxZ86Wa7fGXlvcrG?usp=sharing
     -This link will be taken down after I download

**Comment by BioinformaticEmilio** [comment]
Thank you for being so thorough!

So now it works! :) 

I didn't get to step 3. I had an older version of Rx64 3.3.1 , but the installer got me 3.4.2 . Since the program was running (but not converting files) I didn;t think that was an issue. I just uninstalled everything, and installed everything again and it does the job now.

Thanks again!

**Comment by chasemc** [comment]
Great!
